# Workflow for testing Sophie

name: Sophie Tests

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  linux-bash:
    # The type of runner that the job will run on
    name: bash conformance
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.0

      # Runs a multiple commands using the runners shell
      - name: Sophie self-lint
        run: |
          cd $GITHUB_WORKSPACE
          ./sophie
